config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  get "publics/about" => "publics#about"
  get "publics/contact" => "publics#contact"
  root to: "publics#about"
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :room_users, only: :destroy
    resources :contents, only: [:index, :create, :destroy] do
      resources :reads, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :reads, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :content_type, presence: true
  validates :content_title, presence: true
  validates :content_text, presence: true
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :contents, dependent: :destroy

  validates :room_name, presence: true
  validate :user_ids_duplicate

  def user_ids_duplicate
    if (user_ids.count - user_ids.uniq.count) > 0
      errors.add(:user_ids, "同じユーザーが登録されています")
    end
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :room_id, uniqueness: { message: "同じユーザーが登録されています", scope: [:user_id] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :contents
  has_many :reads
  has_many :comments
  has_one_attached :avatar

  validates :user_name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'Include both letters and numbers', allow_blank: true }

  def read_by?(content_id)
    reads.where(content_id: content_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :avatar])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(comment_params)
    redirect_to room_contents_path(params[:room_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to room_contents_path(params[:room_id])
  end

  private

  def comment_params
    params
    .require(:comment)
    .permit(:comment_text)
    .merge(user_id: current_user.id, content_id: params[:content_id])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @current_room = Room.find(params[:room_id])
    @content = Content.new
    @contents = @current_room.contents.includes(:user)
    @comment = Comment.new
    @room_user = RoomUser.where(user_id: current_user.id).where(room_id: params[:room_id])
  end

  def create
    @current_room = Room.find(params[:room_id])
    @room_user = RoomUser.where(user_id: current_user.id).where(room_id: params[:room_id])
    @content = Content.new(content_params)
    if @content.save
      redirect_to room_contents_path(@current_room)
    else
      @contents = @current_room.contents.includes(:user)
      render :index
    end
  end

  def destroy
    content = Content.find(params[:id])
    content.destroy
    redirect_to room_contents_path(params[:room_id])
  end

  private
  def content_params
    params
    .require(:content)
    .permit(:content_type, :content_title, :content_text)
    .merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def about
    @user = User.new
    @room = Room.new
    @current_room = Room.new #エラー回避(仮)
  end

  def contact
    @user = User.new
    @room = Room.new
    @current_room = Room.new #エラー回避(仮)
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  def create
    @current_room = Room.find(params[:room_id])
    Read.create(user_id: current_user.id, content_id: params[:content_id])
    redirect_to room_contents_path(@current_room)
  end

  def destroy
    @current_room = Room.find(params[:room_id])
    Read.find_by(user_id: current_user.id, content_id: params[:content_id]).destroy
    redirect_to room_contents_path(@current_room)
  end
end

app/controllers/room_users_controller.rb
class RoomUsersController < ApplicationController

  def destroy
    room_user = RoomUser.find(params[:id])
    content_ids = Content.where(room_id: params[:room_id]).ids
    reads = Read.where(user_id: current_user.id).where(content_id: content_ids)
    room_user.destroy
    reads.destroy_all
    redirect_to root_path
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @room = Room.new
    @current_room = Room.new #エラー回避(仮)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params
    .require(:room)
    .permit(:room_name, user_ids: [])
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    auth_options = { scope: resource_name, recall: "#{controller_path}#failed" }
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  def failed
    flash[:alert] = "メールアドレスまたはパスワードが違います。"
    redirect_to params[:user][:url]
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/reads_helper.rb
module ReadsHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/contents/_content.html.erb
<div class="content">
<div class="user-avatar">
  <i class="fas fa-user"></i>
</div>
<% case content.content_type %>
<% when "report" then %>
  <div class="report">
<% when "communicate" then %>
  <div class="communicate">
<% when "consult" then %>
  <div class="consult">
<% end %>
    <div class="upper-message">
      <div class="message-user">
        <%= content.user.user_name %>さんより
        <%= content.content_title %>についての
        <% case content.content_type %>
        <% when "report" then %>
        報告があります
        <% when "communicate" then %>
        連絡があります
        <% when "consult" then %>
        相談があります
        <% end %>
      </div>
    </div>

    <% if content.user == current_user %>
      <%= link_to room_content_path(params[:room_id], content.id), method: :delete, class: "content-destroy" do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    <% end %>

    <div class="message-content">
      <%= safe_join(content.content_text.split("\n"),tag(:br)) %>
    </div>

    <div class="lower-message">
      <div class="message-date">
          <%= l content.created_at %>
      </div>
      <div class="reads">
        <% if current_user.read_by?(content.id) %>
          <%= link_to room_content_read_path(content.room_id, content.id, content), class: "un-read-link", method: :DELETE do %>
            <i class="fas fa-check-square"></i>
          <% end %>
        <% else %>
          <%= link_to room_content_reads_path(content.room_id, content.id), class: "read-link", method: :POST do %>
            <i class="far fa-check-square"></i>
          <% end %>
        <% end %>
        <span class="reads-count">
          <%= content.reads.count %>
          /
          <%= content.room.user_ids.count %>
        </span>
      </div>
      <div class="comment-btn-group">
        <div class="comment-btn">
          <i class="fas fa-comment-dots"></i>
        </div>
        <div class="comments-count">
          <%= content.comments.count %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="comment-wrapper">
  <div class="comments">
    <% content.comments.each do |c| %>
      <div class="comment">
        <div class="comment-left">
          <div class="comment-user">
            <%= c.user.user_name %>
          </div>
          <div class="comment-bottom">
            <% if c.user == current_user %>
              <%= link_to room_content_comment_path(params[:room_id], content.id, c.id), method: :delete, class: "comment-destroy" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
            <p class="comment-time">
              <span><%= l c.created_at %></span>
            </p>
            <div class="comment-text">
              <%= c.comment_text %>
            </div>
          </div>
        </div>
        <div class="comment-right">
          <div class="user-avatar">
            <i class="fas fa-user"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= form_with model: @comment, url: room_content_comments_path(params[:room_id], content.id), local: true, class: "comment-form-group" do |f| %>
    <%= f.text_field :comment_text, class: "comment-form" %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "comment-submit" do %>
      <i class="fas fa-comment-dots"></i>
    <% end %>
  <% end %>
</div>

app/views/contents/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "shared/side_bar" %>
  </div>
  <div class="chat">
    <%= render "shared/main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "shared/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>

    <%= render 'shared/error_messages', model: f.object %>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :room_name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]" class="room-user-form">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.user_name %></option>
          <% end %>
        </select>
        <div class="user-form-buttons">
          <button type="button" class="btn-clone">追加</button>
          <button type="button" class="btn-remove">削除</button>
        </div>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>