config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  get "publics/about" => "publics#about"
  get "publics/contact" => "publics#contact"
  root to: "publics#about"
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :room_users, only: :destroy
    resources :contents, only: [:index, :create, :destroy] do
      resources :reads, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :reads, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :content_type, presence: true
  validates :content_title, presence: true
  validates :content_text, presence: true
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :contents, dependent: :destroy

  validates :room_name, presence: true
  validate :user_ids_duplicate

  def user_ids_duplicate
    if (user_ids.count - user_ids.uniq.count) > 0
      errors.add(:user_ids, "同じユーザーが登録されています")
    end
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :room_id, uniqueness: { message: "同じユーザーが登録されています", scope: [:user_id] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :contents
  has_many :reads
  has_many :comments
  has_one_attached :avatar

  validates :user_name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'Include both letters and numbers', allow_blank: true }

  def read_by?(content_id)
    reads.where(content_id: content_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :avatar])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(comment_params)
    redirect_to room_contents_path(params[:room_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to room_contents_path(params[:room_id])
  end

  private

  def comment_params
    params
    .require(:comment)
    .permit(:comment_text)
    .merge(user_id: current_user.id, content_id: params[:content_id])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @current_room = Room.find(params[:room_id])
    @content = Content.new
    @contents = @current_room.contents.includes(:user)
    @comment = Comment.new
    @room_user = RoomUser.where(user_id: current_user.id).where(room_id: params[:room_id])
  end

  def create
    @current_room = Room.find(params[:room_id])
    @room_user = RoomUser.where(user_id: current_user.id).where(room_id: params[:room_id])
    @content = Content.new(content_params)
    if @content.save
      redirect_to room_contents_path(@current_room)
    else
      @contents = @current_room.contents.includes(:user)
      render :index
    end
  end

  def destroy
    content = Content.find(params[:id])
    content.destroy
    redirect_to room_contents_path(params[:room_id])
  end

  private
  def content_params
    params
    .require(:content)
    .permit(:content_type, :content_title, :content_text)
    .merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def about
    @user = User.new
    @room = Room.new
    @current_room = Room.new #エラー回避(仮)
  end

  def contact
    @user = User.new
    @room = Room.new
    @current_room = Room.new #エラー回避(仮)
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  def create
    @current_room = Room.find(params[:room_id])
    Read.create(user_id: current_user.id, content_id: params[:content_id])
    redirect_to room_contents_path(@current_room)
  end

  def destroy
    @current_room = Room.find(params[:room_id])
    Read.find_by(user_id: current_user.id, content_id: params[:content_id]).destroy
    redirect_to room_contents_path(@current_room)
  end
end

app/controllers/room_users_controller.rb
class RoomUsersController < ApplicationController

  def destroy
    room_user = RoomUser.find(params[:id])
    content_ids = Content.where(room_id: params[:room_id]).ids
    reads = Read.where(user_id: current_user.id).where(content_id: content_ids)
    room_user.destroy
    reads.destroy_all
    redirect_to root_path
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @room = Room.new
    @current_room = Room.new #エラー回避(仮)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params
    .require(:room)
    .permit(:room_name, user_ids: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/reads_helper.rb
module ReadsHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spinach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @current_room.room_name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <% if @current_room.user_ids.count > 1 %>
        <%= link_to room_room_user_path(params[:room_id], @room_user.ids), class: "room_user_destroy", method: :delete do %>
          <i class="far fa-times-circle"></i>
        <% end %>
      <% else %>
        <%= link_to room_path(params[:room_id]), class: "room_destroy", method: :delete do %>
          <i class="far fa-times-circle"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="messages">
  <div id="scroll-inner">
    <%= render partial: 'content', collection: @contents %>
  </div>
</div>

<%= form_with model: [@current_room, @content], class: 'form', local: true do |f| %>
  <div class="content-title-type-forms">
    <%= f.text_field :content_title, class: 'content-title-form' %>
    <span>についての</span>
    <div class="radio-buttons">
      <label><%= f.radio_button :content_type, "report" %>報告</label>
      <label><%= f.radio_button :content_type, "communicate" %>連絡</label>
      <label><%= f.radio_button :content_type, "consult" %>相談</label>
    </div>
  </div>
  <div class="form-input">
    <%= f.text_area :content_text, class: 'form-message' %>
    <%# <label class="form-image">
      <span class="image-file">画像</span> %>
      <%# <%= f.file_field :image, class: 'hidden' %>
    <%# </label> %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "form-submit" do %>
      <i class="fas fa-arrow-circle-up"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_side_bar.html.erb
<% if user_signed_in? %>
  <div class="side-bar-header">
    <%= link_to "#", class: "user-edit-link" do %>
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar %>
        <%= current_user.user_name %>
      <% else %>
        <%= image_tag "default-avatar.png" %>
        <%= current_user.user_name %>
      <% end %>
    <% end %>
    <div class="log-out-link">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="session-links">
    <button type="button" id="sign-in-modal-open-btn">ログイン</button>
    <button type="button" id="sign-up-modal-open-btn">新規登録</button>
  </div>
<% end %>

<div class="side-bar-main">
  <% if user_signed_in? %>
    <% current_user.rooms.each do |room| %>
      <% if room.id == @current_room.id %>
        <div class="selected room">
          <div class="room-name">
            <%= link_to room_contents_path(room) do %>
              <i class="fas fa-door-open"></i>
              <%= room.room_name %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="room">
          <div class="room-name">
            <%= link_to room_contents_path(room) do %>
              <i class="fas fa-door-closed"></i>
              <%= room.room_name %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="create-room">
      <%= link_to new_room_path do %>
        <i class="fas fa-plus"></i>
        <span>新しく部屋を作成する</span>
      <% end %>
    </div>
  <% end %>
</div>

<div class="side-bar-footer">
  <div class="logo">
    <%= image_tag "spinach-logo.png", class: "spinach-logo-image" %>
    <h1 class="spinach-logo-character">Spinach</h1>
  </div>
  <% if current_page?(root_path) %>
    <div class="selected footer-link">
      <%= link_to root_path do %>
        <i class="far fa-question-circle"></i>
        <span>about Spinach</span>
      <% end %>
    </div>
  <% else %>
    <div class="footer-link">
      <%= link_to root_path do %>
        <i class="far fa-question-circle"></i>
        <span>about Spinach</span>
      <% end %>
    </div>
  <% end %>
  <div class="footer-link">
    <%= link_to "#" do %>
    <i class="far fa-envelope"></i>
    <span>contact</span>
    <% end %>
  </div>
</div>

app/views/shared/_sign_in_modal.html.erb
<div id="sign-in-modal-overlay">
  <div id="sign-in-modal-window">
    <div class="sign-in-modal-header">
      <div class="sign-in-modal-title">
        <%= image_tag "spinach-logo.png", class: "spinach-logo-image" %>
        <h1>Spinachにログイン</h1>
      </div>
    </div>
    <button id="sign-in-modal-close-btn"><i class="fas fa-times"></i></button>
    <%= form_with model: @user, url: user_session_path, local: true do |f| %>
      <div class="sign-in-email">
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: "sign-in-email-form" %>
      </div>
      <div class="sign-in-password">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "sign-in-password-form" %>
      </div>
        <%= f.hidden_field :url, value: request.fullpath %>
        <%= f.submit "ログイン", class: "sign-in-btn" %>
        <div class="sign-in-to-sign-up">
          <%# <button id="sign-in-to-sign-up-btn">新規登録はこちら</button> %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_sign_up_modal.html.erb
<div id="sign-up-modal-overlay">
  <div id="sign-up-modal-window">
    <div class="sign-up-modal-header">
      <div class="sign-up-modal-title">
        <%= image_tag "spinach-logo.png", class: "spinach-logo-image" %>
        <h1>Spinachに新規登録</h1>
      </div>
    </div>
    <button id="sign-up-modal-close-btn"><i class="fas fa-times"></i></button>
    <%= form_with model: @user, url: user_registration_path, local: true do |f| %>
      <div class="sign-up-email">
        <%= f.label :email, "メールアドレス ※必須" %>
        <%= f.email_field :email, class: "sign-up-email-form" %>
      </div>
      <div class="sign-up-password">
        <%= f.label :password, "パスワード ※必須" %>
        <%= f.password_field :password, class: "sign-up-password-form" %>
      </div>
      <div class="sign-up-password-confirmation">
        <%= f.label :password_confirmation, "パスワード(確認) ※必須" %>
        <%= f.password_field :password, class: "sign-up-password-confirmation-form" %>
      </div>
      <div class="sign-up-user-name">
        <%= f.label :user_name, "ユーザー名 ※必須" %>
        <%= f.text_field :user_name, class: "sign-up-user-name-form" %>
      </div>
      <div class="sign-up-avatar">
        <%= f.label :avatar, "ユーザー画像" %>
        <%= f.file_field :avatar %>
      </div>
        <%= f.hidden_field :url, value: request.fullpath %>
        <%= f.submit "新規登録", class: "sign-up-btn" %>
        <div class="sign-up-to-sign-in">
          <%# <button id="sign-up-to-sign-in-btn">ログインはこちら</button> %>
        </div>
      <% end %>
  </div>
</div>